# No password variable exists in this module by design. The master password is
# generated by random_password and written directly to Secrets Manager, so it is never
# supplied as an input, never appears in a tfvars file, and is never an output.

variable "name_prefix" {
  type        = string
  description = "Prefix applied to every resource name in this module."
}

variable "subnet_ids" {
  type        = list(string)
  description = "Isolated subnets for the DB subnet group."

  validation {
    condition     = length(var.subnet_ids) >= 2
    error_message = "RDS requires a subnet group spanning at least two availability zones, even for a single-AZ instance."
  }
}

variable "security_group_ids" {
  type        = list(string)
  description = "Security groups attached to the instance."
}

variable "engine_version" {
  type        = string
  description = "PostgreSQL major version. Minor upgrades are applied automatically in the maintenance window."
  default     = "16"

  validation {
    condition     = can(regex("^[0-9]+(\\.[0-9]+)?$", var.engine_version))
    error_message = "engine_version must be a major version such as 16, or a major.minor version."
  }
}

variable "instance_class" {
  type        = string
  description = "RDS instance class."
  default     = "db.t4g.micro"

  validation {
    condition     = can(regex("^db\\.[a-z0-9]+\\.[a-z0-9]+$", var.instance_class))
    error_message = "instance_class must be a valid RDS instance class, for example db.t4g.micro."
  }
}

variable "allocated_storage" {
  type        = number
  description = "Initial storage in GiB."
  default     = 20

  validation {
    condition     = var.allocated_storage >= 20
    error_message = "allocated_storage must be at least 20 GiB."
  }
}

variable "max_allocated_storage" {
  type        = number
  description = "Ceiling in GiB for storage autoscaling. Set equal to allocated_storage to disable it."
  default     = 100

  validation {
    condition     = var.max_allocated_storage >= 20
    error_message = "max_allocated_storage must be at least 20 GiB."
  }
}

variable "db_name" {
  type        = string
  description = "Name of the initial database created on the instance."
  default     = "pipeline"

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9_]{0,62}$", var.db_name))
    error_message = "db_name must start with a letter and contain only letters, digits and underscores."
  }
}

variable "master_username" {
  type        = string
  description = "Master username. Not a secret; the password it pairs with is generated and stored separately."
  default     = "pipeline_admin"

  validation {
    condition     = !contains(["admin", "postgres", "root"], var.master_username)
    error_message = "master_username must not be a reserved or guessable name such as admin, postgres or root."
  }
}

variable "secret_name" {
  type        = string
  description = "Secrets Manager secret name for the credentials. Passed in rather than derived, because the security module scopes its IAM policy to this same name."
}

variable "backup_retention_days" {
  type        = number
  description = "Days of automated backups to retain."
  default     = 7

  validation {
    condition     = var.backup_retention_days >= 1 && var.backup_retention_days <= 35
    error_message = "backup_retention_days must be between 1 and 35."
  }
}

variable "backup_window" {
  type        = string
  description = "Daily backup window in UTC. Set to the small hours in the deployment region."
  default     = "17:00-18:00" # 01:00-02:00 in ap-southeast-1
}

variable "maintenance_window" {
  type        = string
  description = "Weekly maintenance window in UTC, placed after the backup window."
  default     = "Sun:18:30-Sun:19:30" # Mon 02:30-03:30 in ap-southeast-1
}

variable "multi_az" {
  type        = bool
  description = "Whether to run a standby in a second AZ. False in this environment as a documented simplification; production would set it true."
  default     = false
}

variable "secret_recovery_window_days" {
  type        = number
  description = "Days Secrets Manager retains a deleted secret before purging it. Zero allows immediate reuse of the name, which matters when tearing a dev environment down and back up."
  default     = 7

  validation {
    condition     = var.secret_recovery_window_days == 0 || (var.secret_recovery_window_days >= 7 && var.secret_recovery_window_days <= 30)
    error_message = "secret_recovery_window_days must be 0, or between 7 and 30."
  }
}

variable "deletion_protection" {
  type        = bool
  description = "Whether the instance refuses deletion."
  default     = true
}

variable "skip_final_snapshot" {
  type        = bool
  description = "Whether to skip the final snapshot on destroy. True only for disposable environments."
  default     = false
}

variable "performance_insights_enabled" {
  type        = bool
  description = "Whether to enable Performance Insights. Free at seven days' retention on supported classes."
  default     = true
}

variable "monitoring_interval_seconds" {
  type        = number
  description = "Enhanced monitoring granularity. Zero disables it and avoids the extra IAM role and CloudWatch cost."
  default     = 0

  validation {
    condition     = contains([0, 1, 5, 10, 15, 30, 60], var.monitoring_interval_seconds)
    error_message = "monitoring_interval_seconds must be 0, 1, 5, 10, 15, 30 or 60."
  }
}

variable "log_min_duration_statement_ms" {
  type        = number
  description = "Statements slower than this are logged. Tuned to catch the transformation's write path without logging every query."
  default     = 1000
}
