# Development environment values.
#
# Nothing in this file is a secret. The only credential in the stack is the database
# password, which is generated by random_password and written straight to Secrets
# Manager — it is never an input, a variable, or an output.

project     = "datapipe"
environment = "dev"
owner       = "platform-team"
aws_region  = "ap-southeast-1"

vpc_cidr = "10.0.0.0/16"
az_count = 2

# CI overwrites these with the immutable digest-tagged build it just pushed.
api_image_tag    = "latest"
worker_image_tag = "latest"

# Two API tasks so a deployment or an AZ loss does not take the API down; one worker,
# because the sample workload is a handful of runs per day.
api_desired_count    = 2
worker_desired_count = 1

# Smallest instance that runs PostgreSQL 16 comfortably for this data volume.
db_instance_class    = "db.t4g.micro"
db_allocated_storage = 20

# Dev: short retention, no deletion protection, so the environment is disposable.
log_retention_days     = 30
db_deletion_protection = false
